import type { UserlensRunResult } from './client';
import { computeUxScore } from './score';

type RunForComposer = {
  id: number;
  url: string;
  tests: string[];
  status: string;
  smokeOk?: boolean | null;
  a11yViolations?: number | null;
  lighthousePerformance?: number | null;
  lighthouseAccessibility?: number | null;
  lighthouseSeo?: number | null;
  lighthouseBestPractices?: number | null;
  error?: string | null;
  results?: unknown;
};

export function buildComposerPrompt(run: RunForComposer): string {
  const results = run.results as UserlensRunResult | undefined;
  const uxScore = computeUxScore(run);
  const lines: string[] = [
    '# UserLens UX Fix Request',
    '',
    `Analyze and fix UX issues for: **${run.url}**`,
    '',
    '## Context',
    `- Run #${run.id} · Status: ${run.status}`,
    `- Tests: ${run.tests.join(', ')}`,
    uxScore != null ? `- UX Score: ${uxScore}/100` : '',
    '',
    '## Issues to address (priority order)',
  ].filter(Boolean);

  if (run.smokeOk === false) {
    lines.push(
      '',
      '### 🔴 Critical — Page load / smoke test failed',
      results?.smoke?.error
        ? `- Error: ${results.smoke.error}`
        : `- HTTP ${results?.smoke?.statusCode ?? 'unknown'} — page did not load successfully`,
      '- Fix routing, deployment, or server errors so the page returns 200 OK',
    );
  }

  if ((run.a11yViolations ?? 0) > 0) {
    lines.push(
      '',
      `### 🔴 Accessibility — ${run.a11yViolations} axe-core violation(s)`,
    );
    const summary = results?.a11y?.summary ?? [];
    if (Array.isArray(summary) && summary.length > 0) {
      for (const v of summary.slice(0, 8)) {
        const item = v as { id?: string; impact?: string; description?: string; nodes?: number };
        lines.push(`- [${item.impact ?? 'unknown'}] **${item.id}**: ${item.description} (${item.nodes ?? 0} nodes)`);
      }
    } else {
      lines.push('- Run axe-core audit and fix color contrast, labels, ARIA, and keyboard navigation');
    }
  }

  if (run.lighthousePerformance != null && run.lighthousePerformance < 70) {
    lines.push(
      '',
      `### 🟡 Performance — Lighthouse score ${run.lighthousePerformance}/100 (desktop)`,
      '- Optimize LCP, reduce JS bundle size, lazy-load images, enable caching',
    );
  }

  const mobile = results?.lighthouseMobile;
  if (mobile?.performance != null && mobile.performance < 70) {
    lines.push(
      '',
      `### 🟡 Mobile performance — ${mobile.performance}/100`,
      '- Improve mobile viewport rendering, touch targets (min 44px), and reduce layout shift',
    );
  }

  if (run.lighthouseAccessibility != null && run.lighthouseAccessibility < 90) {
    lines.push(
      '',
      `### 🟡 Lighthouse accessibility — ${run.lighthouseAccessibility}/100`,
      '- Fix semantic HTML, focus order, and screen-reader announcements',
    );
  }

  if (run.lighthouseSeo != null && run.lighthouseSeo < 90) {
    lines.push(
      '',
      `### 🟢 SEO — ${run.lighthouseSeo}/100`,
      '- Add meta description, canonical URL, structured data, and descriptive title tags',
    );
  }

  if (run.error) {
    lines.push('', `### Error during scan`, `- ${run.error}`);
  }

  lines.push(
    '',
    '## Instructions for Composer',
    '1. Open the codebase that deploys to this URL',
    '2. Fix each issue above without breaking existing functionality',
    '3. Match the existing design system (Tailwind/shadcn patterns if present)',
    '4. After fixes, re-run UserLens full scan to verify score improvement',
    '',
    '---',
    '_Generated by UserLens • MsgNexus Admin_',
  );

  return lines.join('\n');
}